# ResourceManager Service
apiVersion: v1
kind: Service
metadata:
  name: hadoop-resourcemanager
  labels:
    app: hadoop
    component: resourcemanager
spec:
  type: NodePort
  ports:
    - name: web
      port: 8088
      targetPort: 8088
      nodePort: {{ .Values.web.resourcemanager }}
    - name: scheduler
      port: 8030
      targetPort: 8030
    - name: tracker
      port: 8031
      targetPort: 8031
    - name: admin
      port: 8032
      targetPort: 8032
  selector:
    app: hadoop
    component: resourcemanager