apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
  labels:
    app: hadoop
    component: namenode
spec:
  serviceName: hadoop-namenode
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      component: namenode
  template:
    metadata:
      labels:
        app: hadoop
        component: namenode
    spec:
      hostname: namenode
      containers:
        - name: namenode
          image: docker.1ms.run/apache/hadoop:3
          command: ["sh", "-c", "mkdir -p /opt/hadoop/etc/hadoop && echo '<?xml version=\"1.0\" encoding=\"UTF-8\"?><configuration><property><name>fs.defaultFS</name><value>hdfs://0.0.0.0:8020</value></property></configuration>' > /opt/hadoop/etc/hadoop/core-site.xml && echo '<?xml version=\"1.0\" encoding=\"UTF-8\"?><configuration><property><name>dfs.replication</name><value>1</value></property><property><name>dfs.namenode.name.dir</name><value>/tmp/hadoop-root/dfs/name</value></property></configuration>' > /opt/hadoop/etc/hadoop/hdfs-site.xml && mkdir -p /tmp/hadoop-root/dfs/name && chmod -R 777 /tmp/hadoop-root && hdfs namenode -format -force && hdfs namenode -Ddfs.namenode.rpc-bind-host=0.0.0.0"]
          ports:
            - containerPort: 9870  # Web UI
            - containerPort: 8020  # RPC
          env:
            - name: HADOOP_USER_NAME
              value: "root"  # 避免权限问题
---

apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
spec:
  selector:
    app: hadoop
    component: namenode
  type: NodePort
  ports:
    - name: web-ui
      port: 9870
      targetPort: 9870
      nodePort: 30072
    - name: rpc
      port: 8020
      targetPort: 8020